nodeLinker: node-modules

pnpMode: loose

packageExtensions:
  "@vitejs/plugin-vue@*":
    peerDependencies:
      vue: "*"
  "@tiptap/core@*":
    peerDependencies:
      "@tiptap/pm": "*"
  "@tiptap/extension-floating-menu@*":
    peerDependencies:
      "@tiptap/pm": "*"
  "@tiptap/extension-bubble-menu@*":
    peerDependencies:
      "@tiptap/pm": "*"
